import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Oswald } from "next/font/google";

const oswald = Oswald({
  subsets: ["latin"],
  weight: "700",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "100",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} ${montserrat} antialiased min-h-screen bg-[#FFFFFF] overflow-x-clip`}
      >
        {children}
      </body>
    </html>
  );
}
